windicss/docs

.vitepress/config.js, guide/cli.md, guide/index.md, guide/introduction.md, guide/migration.md, guide/svelte.md, guide/vite.md, guide/vue.md
This pull request adds installation instructions for all available packages, extracted from their respective READMEs.
Usage instructions should probably live on a common page, since it's very similar on all frameworks.
Also, made the _Migration_ section framework-agnostic; linking to it from all installation pages.
=> feat: add installation instructions for all frameworks and flavors

guide/migration.md
```
- "tailwindccs": "*",
+ "tailwindcss": "*",
```
=> fix: typo in migration.md

guide/directives.md
Hi!
If I'm not wrong, `@layer` directive support has been implemented in https://github.com/windicss/windicss/pull/143, thanks to @voorjaar.
Let's mark it as supported here!
Should I had an example of usage, or the Tailwind documentation is enough?
Thanks.
=> guide(directives): mark "@layer" directive as supported

guide/svelte.md
updated svelte-windicss-preprocess v3.1.4 to use different syntax for variant attributes.
=> docs: adapt svelte guide to latest update

guide/svelte.md
The SSR `noExternal` directive has been removed from the SvelteKit templates and is no longer recommended.
=> Remove outdated SvelteKit configuration

guide/extractions.md
I think the example is a pseudo code (since there is no range function?!) but it looks wrong compared to the next line https://github.com/windicss/docs/edit/main/guide/extractions.md#L49
=> Small typo in `safelist` example

integrations/svelte.md
a quick rework of the integration guide of svelte, to clarify the process with vite
also removed sapper instructions, since svelte-kit is replacing it
=> refactor: rework svelte integration guide

integrations/vite.md
As someone recently did the same thing at one of my projects, I feel no shame anymore to create stupidly simple PRs 😉
=> fix: typo in module name

features/value-auto-infer.md
"border" was mispelled as "background"
=> chore: typo

.vitepress/config/sidebar.ts, .vitepress/theme/components/logos/Logo.vue, guide/installation.md, integrations/javascript.md
I've previously opened up [this](https://github.com/windicss/windicss/issues/293) issue about how to consume the Javascript API of Windi CSS, and was given some good example files.
But I'd like it if they were added to the docs so that other developers won't have to open the same issues again.
Let me know if you would like to change some wording, or I have a misspelling, or anything I need to change.
=> Add Javascript API integrations page

features/index.md
Incorrect: tailwind-`liked`
Correct: tailwind-`like`
=> fix: typo in /features

plugins/community/question-mark.md
In line 17 it's
>Then add the plugin to your `tailwind.config.js` file:
while in line 20 it's 
> // windi.config.js
=> docs: make context consistent

integrations/rollup.md
I just noticed that the documentation was for the rollup bundler but the config files references are for vite. so I changed all `vite.confi.ts` to `rollup.config.js` and also changed the code block language from `ts` to `js`.
=> Chang config file names to'rollup.config.js'

integrations/webpack.md
Makes the solution to https://github.com/windicss/windicss-webpack-plugin/issues/84 more obvious
=> doc(webpack): add configuration example for non-es module syntax

.vitepress/config/sidebar.ts, features/index.md, features/rtl.md
- update document for RTL
I commented the RTL example code because I didn’t find the `@windicss/vitepress-theme` package in windicss repo. By providing component to switch `RTL`, it seems to be very useful like the example code for dark mode.
=> docs: update features/RTL document

features/value-auto-infer.md
=> fix a typo

integrations/vite.md
Fix typo in `vite.md`
I believe the file being referred to for safelist is `windi.config.ts` and not `vite.config.js`
=> chore: fix typo 

plugins/official/typography.md
As a new Windi user I stumbled on this issue where I needed to add the `prose` class to a wrapping element. For this I had to read the Tailwind docs to find out. To avoid wasted time for other new users I've added it to this page.
=> Extend typography readme with "prose" class usage

integrations/vite.md
* Change WindiCSS.default() to WindiCSS() in line with https://github.com/windicss/vite-plugin-windicss/commit/713743f
* Use diff codebock instead of js to better show what needs to be added
* Version should be next-102, which is when $layout was renamed to __layout, not next-100
* Added comments as they actually appear on the config
* Changed the last $layout to __layout
=> docs: update vite sveltekit integration instructions

.vitepress/theme/components/molecules/DropdownLink.vue
Closes #142.
Limits the max height of dropdown menus and adds a scrollbar if content overflows:
https://user-images.githubusercontent.com/43280336/140237971-f750f5c8-21c7-4870-93b3-47bf133ea80b.mov
=> fix: dropdown menu content overflow

features/analyzer.md, features/attributify.md, features/dark-mode.md, features/directives.md, features/important-prefix.md, features/index.md, features/responsive-design.md, features/rtl.md, features/shortcuts.md, features/value-auto-infer.md, features/variant-groups.md, guide/migration.md
this affects the sections:
- Guide
- Features
but not the section `Integrations`.
As I'm not a native speaker I only made changes where I felt confident enough. I also encountered two different spellings of "analyzer"/"analyser" whereas it would be good to keep the spelling uniform (helpful when running a text search). "Analyzer" is American English and probably more common.
I recommend squash merging due to the many individual commits :wink:
=> docs: corrected spelling & rewrote parts for better grammar 

utilities/colors.md
In the original config, all colors are overwritten and the other colors disappear.
=> docs: update colors.md

integrations/vue-cli.md
I am a vue2 & ts developer, and when I use `vue add windicss` according to the document, it does not take effect. After checking the vue cli plugin documentation, I found that I need to add `import 'windi.css'` in  my main.ts to take effect, so I added it.
=> docs: Add import docs in vue-cli docs

posts/v34.md
Should be `zinc`
There's a warning: https://github.com/windicss/windicss/blob/67802fe9af47ebcbebd5c5ee4e5cefc740e39506/src/config/colors.ts#L355
=> fix: typo in zinc

integrations/nuxt.md
On the Nuxt integration page, rename `webpack.config.js` to `windi.config.js`.
=> docs: fix typo

plugins/official/typography.md
In https://github.com/windicss/windicss/issues/290, the lack of documentation was mentioned and I've also stumbled upon this when building my blog. So I think adding info about this plugin settings should be a good idea.
=> docs: add info about typography plugin settings

utilities/general/variants.md
Add pseudo element content example in docs as suggested here (windicss/windicss#658).
Hope this would help someone who needs references or simply wants to add `content: ''`.
If something is missing, please kindly edit.
=> feat: add pseudo element content examples in docs

integrations/nuxt.md
Change the property from `buildModules` to `modules` because. `buildModules` is no longer needed in Nuxt 3 and Nuxt Bridge. All modules should be added to `modules` instead.
=> docs: Changed the Property nuxt config  for nuxt 3.

posts/attributify.md
The [Attributify Mode](https://windicss.org/posts/attributify.html) post is used as a reference for the [attributify feature](https://windicss.org/features/attributify.html#utilities). Fixes are made to help reading.
Changes
- fix the Markdown format
- fix grammar issues
- format Markdown tables
Example
- Previous
- Fixed
=> docs: fix Markdown format & grammar

integrations/vite.md
You are now meant to use the `vite.config.js` file, instead of `config.vite`. Routes are also now added with `+` instead of `__`.
=> docs: update SvelteKit install instructions

integrations/nuxt.md
```js
import { defineNuxtConfig } from 'nuxt3'
```
no longer works and previously had a deprecation message.
=> docs: update defineNuxtConfig import
