guide/plugins.md, index.md
feat: add scroll-snap plugin
refactor: add current year
=> feat: add scroll-snap plugin

guide/index.md
=> chore: fix typo

utilities/sizing.md
=> fix: sizing table

guide/integrations/svelte-preprocess.md
Added bash section for people not familiar installing Svelte on Vite. Remove at will if you find it not in line with instructions for other versions.
=> Vite version added to Svelte integrations

guide/svelte.md
In reference to this issue #31
=> fix: Update SvelteKit installation description

guide/integrations/svelte.md
=> docs: adapt svelte guide to latest update

integrations/gridsome.md
_gridsome.config.js_ instead of _ngridsome.config.js_
=> chore: typo in gridsome integration

.vitepress/theme/components/HomeHero.vue, .vitepress/theme/components/navbar/NavBarDropdownLink.vue
I think this makes the page look a bit better.
Also fixes an issue for smaller screens where these menus used to get out of the viewport on small screens (they have scrolls now).
=> refactor: improve and center hero content

integrations/svelte.md
Get windi working with the latest svelte kit.
=> Add Specific Instructions for Svelte Kit

integrations/webpack.md
Fixes https://github.com/windicss/windicss-webpack-plugin/issues/79
=> feat(webpack): add storybook integration documentation

guide/configuration.md, guide/extractions.md, guide/index.md, guide/installation.md, guide/migration.md, integrations/vite.md
Made edits to all pages in the 'Guide' section. Changes include typos, grammar, sentence restructuring and so on. Technical details in the docs are untouched.
=> docs: revise

integrations/vite.md
Reference: https://kit.svelte.dev/docs#layouts
=> Change $layout.svelte to __layout.svelte

guide/configuration.md
=> docs: remove double extends?

posts/story.md
Made some grammatical and sentence fixes like changing "he" to it while referring to Tailwind CSS. Also Capitalized some first letters of the sentences.
=> fix: minor grammatical and sentence framing mistakes

plugins/interfaces.md
This PR will fix the missing callback function in the `Add Variants` examples.
=> fix Add Variants example

.vitepress/config/nav.ts, .vitepress/config/sidebar.ts, .vitepress/theme/components/global/playground/PlaygroundWithVariants.vue, package.json, plugins/official/aspect-ratio.md, pnpm-lock.yaml, utilities/behaviors.md, utilities/columns.md, utilities/flexbox.md, utilities/typography.md, utilities/variants.md
This PR updates the docs to be up-to-date with all PRs merged in the [v3.4.0](https://github.com/windicss/windicss/releases/tag/v3.4.0) release.
=> docs: bring docs up-to-date with v3.4.0

integrations/vite.md
closes #152 
preview available here:  
https://deploy-preview-151--windicss.netlify.app/integrations/vite.html#alias-config
=> Alias Docs - reminder about the *prefix

.vitepress/config/nav.ts, .vitepress/config/sidebar.ts
This updates parts of the top nav and the sidebar.
=> chore: adjust top navigation and sidebar

features/attributify.md
- Simple one-sentence change (check diffs).
If this PR gets rejected, there was a grammatical error in it initially; It said "Personally I don't recommend", where it should have been "Personally I don't recommend **it**".
=> Update features/attributify.md to be more professional

integrations/vite.md
from `tailwind.config.js` => `windi.config.js`
=> rename config file name

integrations/vite.md
Saw a small typo while reading the docs.
=> chore: typo vite.md
